name: Build

on:
  push:
    branches: 
      - features/**
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: 
      - develop
      - main
    paths:
      - src/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/AzureMapsControl.Components/AzureMapsControl.Components.csproj